spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loja
    username: root
    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect